export const moodEmojis = {
    "Happy & Energetic": "☀️", "Happy & Calm": "⛅", "Sad & Melancholy": "🌧️",
    "Angry & Energetic": "🌩️", "Neutral & Focused": "☁️", "Confident & Empowered": "🔥",
    "Romantic & Passionate": "💖", "Anxious & Stressed": "🌪️", "Nostalgic & Reflective": "🕰️",
    "Tired & Burned Out": "🌙"
};

export const emotionDictionary = {
    highValence: ['happy', 'cheerful', 'joy', 'hope', 'optimism', 'good', 'excited', 'wonderful', 'blessed', 'great', 'amazing', 'lucky', 'glad', 'thrilled'],
    lowValence: ['sad', 'depressed', 'grey', 'fade', 'rain', 'melancholy', 'lonely', 'upset', 'terrible', 'cry', 'tears', 'hurts', 'awful', 'bad', 'miserable'],
    highEnergy: ['fast', 'loud', 'noisy', 'panic', 'nervous', 'rage', 'energetic', 'power', 'wild', 'mad', 'furious', 'angry', 'pumped'],
    lowEnergy: ['calm', 'fatigue', 'passive', 'slow', 'peaceful', 'quiet', 'relax', 'chill', 'soft', 'bored', 'lazy'],
    nostalgic: ['miss', 'memories', 'past', 'remember', 'childhood', 'old', 'yesterday', 'back then', 'nostalgia', 'longing'],
    anxious: ['stress', 'stressed', 'overwhelmed', 'worry', 'worried', 'nervous', 'panic', 'fear', 'scared', 'pressure', 'anxious'],
    romantic: ['love', 'romantic', 'crush', 'heart', 'passion', 'adore', 'date', 'kiss', 'together', 'sweet', 'affection'],
    confident: ['strong', 'unstoppable', 'boss', 'proud', 'achieved', 'slay', 'win', 'won', 'success', 'confident', 'ready'],
    tired: ['exhausted', 'drained', 'dead', 'done', 'sleep', 'bed', 'rest', 'burned out', 'tired', 'sleepy']
};

export const vibeProfiles = {
    "Happy & Energetic": { id: "37i9dQZF1EVJSvZp5AOML2", youtubeId: "PLRBp0Fe2GpgnIh0AiYKh7o7HnYAej-5ph", val: 85, eng: 80, color1: "#FFD700", singles: [{ title: "Levitating", artist: "Dua Lipa" }, { title: "Walking On Sunshine", artist: "Katrina" }, { title: "Good Days", artist: "SZA" }, { title: "As It Was", artist: "Harry Styles" }, { title: "Blinding Lights", artist: "The Weeknd" }, { title: "Uptown Funk", artist: "Bruno Mars" }, { title: "Happy", artist: "Pharrell Williams" }, { title: "Shake It Off", artist: "Taylor Swift" }, { title: "Can't Stop the Feeling!", artist: "Justin Timberlake" }, { title: "Dance The Night", artist: "Dua Lipa" }] },
    "Happy & Calm": { id: "37i9dQZF1DWSf2RDTDayIx", youtubeId: "PLofht4PTcKYnaH8w5olJCG-FxJphDVMk", val: 75, eng: 30, color1: "#87CEFA", singles: [{ title: "Put Your Records On", artist: "Corinne Bailey Rae" }, { title: "Sunday Morning", artist: "Maroon 5" }, { title: "Banana Pancakes", artist: "Jack Johnson" }, { title: "Here Comes The Sun", artist: "The Beatles" }, { title: "Bubbly", artist: "Colbie Caillat" }, { title: "Sunrise", artist: "Norah Jones" }, { title: "Better Together", artist: "Jack Johnson" }, { title: "Lovely Day", artist: "Bill Withers" }, { title: "Easy", artist: "Commodores" }, { title: "Just the Two of Us", artist: "Grover Washington" }] },
    "Sad & Melancholy": { id: "37i9dQZF1DWVV27DiNWxkR", youtubeId: "PLPE24i8B5jT_l62g2QZz-1HhYF4Y3_N1-", val: 20, eng: 25, color1: "#4682B4", singles: [{ title: "Sparks", artist: "Coldplay" }, { title: "The Night We Met", artist: "Lord Huron" }, { title: "Liability", artist: "Lorde" }, { title: "Skinny Love", artist: "Bon Iver" }, { title: "Someone Like You", artist: "Adele" }, { title: "Fix You", artist: "Coldplay" }, { title: "Breathe Me", artist: "Sia" }, { title: "All I Want", artist: "Kodaline" }, { title: "Say Something", artist: "A Great Big World" }, { title: "Let Her Go", artist: "Passenger" }] },
    "Angry & Energetic": { id: "37i9dQZF1DX1tyCD9QhIWF", youtubeId: "PLW0aKkE9mINJ00sJ25K_eQhD7T3IuE9G0", val: 15, eng: 90, color1: "#DC143C", singles: [{ title: "Misery Business", artist: "Paramore" }, { title: "Break Stuff", artist: "Limp Bizkit" }, { title: "good 4 u", artist: "Olivia Rodrigo" }, { title: "Killing In The Name", artist: "Rage Against The Machine" }, { title: "Smells Like Teen Spirit", artist: "Nirvana" }, { title: "Given Up", artist: "Linkin Park" }, { title: "Duality", artist: "Slipknot" }, { title: "Riot", artist: "Three Days Grace" }, { title: "Bodies", artist: "Drowning Pool" }, { title: "Bulls on Parade", artist: "Rage Against The Machine" }] },
    "Neutral & Focused": { id: "37i9dQZF1DWZeKCadgRdKQ", youtubeId: "PLMIbmfPk1y4XZQsMEHk6Zq0Z2mP2I5Tq1", val: 50, eng: 50, color1: "#9370DB", singles: [{ title: "Clair de Lune", artist: "Claude Debussy" }, { title: "Experience", artist: "Ludovico Einaudi" }, { title: "Weightless", artist: "Marconi Union" }, { title: "Cornfield Chase", artist: "Hans Zimmer" }, { title: "Gymnopédie No.1", artist: "Erik Satie" }, { title: "Nuvole Bianche", artist: "Ludovico Einaudi" }, { title: "Time", artist: "Hans Zimmer" }, { title: "River Flows in You", artist: "Yiruma" }, { title: "Interstellar", artist: "Hans Zimmer" }, { title: "Day One", artist: "Hans Zimmer" }] },
    "Confident & Empowered": { id: "37i9dQZF1DX4eRPd9frC1m", youtubeId: "PLRBp0Fe2GpgnIh0AiYKh7o7HnYAej-5ph", val: 95, eng: 85, color1: "#FF4500", singles: [{ title: "Boss Bitch", artist: "Doja Cat" }, { title: "Stronger", artist: "Kelly Clarkson" }, { title: "Confident", artist: "Demi Lovato" }, { title: "Truth Hurts", artist: "Lizzo" }, { title: "Survivor", artist: "Destiny's Child" }, { title: "Roar", artist: "Katy Perry" }, { title: "Run the World", artist: "Beyoncé" }, { title: "Fighter", artist: "Christina Aguilera" }, { title: "Slay", artist: "Everglow" }, { title: "Juice", artist: "Lizzo" }] },
    "Romantic & Passionate": { id: "37i9dQZF1DX50QitC6Oqtw", youtubeId: "PLofht4PTcKYnaH8w5olJCG-FxJphDVMk", val: 80, eng: 55, color1: "#FF1493", singles: [{ title: "Perfect", artist: "Ed Sheeran" }, { title: "All of Me", artist: "John Legend" }, { title: "Lover", artist: "Taylor Swift" }, { title: "Just the Way You Are", artist: "Bruno Mars" }, { title: "Say You Won't Let Go", artist: "James Arthur" }, { title: "Thinking Out Loud", artist: "Ed Sheeran" }, { title: "A Thousand Years", artist: "Christina Perri" }, { title: "Make You Feel My Love", artist: "Adele" }, { title: "At Last", artist: "Etta James" }, { title: "Unchained Melody", artist: "The Righteous Brothers" }] },
    "Anxious & Stressed": { id: "37i9dQZF1DWZqd5JICZI0u", youtubeId: "PLMIbmfPk1y4XZQsMEHk6Zq0Z2mP2I5Tq1", val: 35, eng: 75, color1: "#808080", singles: [{ title: "Breathin", artist: "Ariana Grande" }, { title: "Help!", artist: "The Beatles" }, { title: "In My Blood", artist: "Shawn Mendes" }, { title: "Heavy", artist: "Linkin Park" }, { title: "Stressed Out", artist: "Twenty One Pilots" }, { title: "Crawling", artist: "Linkin Park" }, { title: "Fake Love", artist: "BTS" }, { title: "Basket Case", artist: "Green Day" }, { title: "Unwell", artist: "Matchbox Twenty" }, { title: "Numb", artist: "Linkin Park" }] },
    "Nostalgic & Reflective": { id: "37i9dQZF1DXc8kgYqQL52I", youtubeId: "PLPE24i8B5jT_l62g2QZz-1HhYF4Y3_N1-", val: 45, eng: 40, color1: "#DAA520", singles: [{ title: "Ribs", artist: "Lorde" }, { title: "Night Changes", artist: "One Direction" }, { title: "7 Years", artist: "Lukas Graham" }, { title: "Castle on the Hill", artist: "Ed Sheeran" }, { title: "Summer of '69", artist: "Bryan Adams" }, { title: "1979", artist: "The Smashing Pumpkins" }, { title: "Kids", artist: "MGMT" }, { title: "Yellow", artist: "Coldplay" }, { title: "100 Years", artist: "Five for Fighting" }, { title: "Photograph", artist: "Ed Sheeran" }] },
    "Tired & Burned Out": { id: "37i9dQZF1DWYcDQ1hSjOpY", youtubeId: "PLPE24i8B5jT_l62g2QZz-1HhYF4Y3_N1-", val: 15, eng: 10, color1: "#708090", singles: [{ title: "Breathe Me", artist: "Sia" }, { title: "Liability", artist: "Lorde" }, { title: "Fix You", artist: "Coldplay" }, { title: "Slow Burn", artist: "Kacey Musgraves" }, { title: "Chasing Pavements", artist: "Adele" }, { title: "The Scientist", artist: "Coldplay" }, { title: "Gravity", artist: "John Mayer" }, { title: "Fade Into You", artist: "Mazzy Star" }, { title: "Landslide", artist: "Fleetwood Mac" }, { title: "Mad World", artist: "Gary Jules" }] }
};

export const quotesDatabase = {
    "Happy & Energetic": [{ text: "Happiness is a choice, not a condition.", author: "Nora Roberts" }],
    "Happy & Calm": [{ text: "I have nothing to do today but smile.", author: "Paul Simon" }],
    "Sad & Melancholy": [{ text: "The wound is the place where the Light enters you.", author: "Rumi" }],
    "Angry & Energetic": [{ text: "Anger is like a storm rising up.", author: "Thich Nhat Hanh" }],
    "Neutral & Focused": [{ text: "Words are our most inexhaustible source of magic.", author: "J.K. Rowling" }],
    "Confident & Empowered": [{ text: "No one can make you feel inferior.", author: "Eleanor Roosevelt" }],
    "Romantic & Passionate": [{ text: "Reality is finally better than your dreams.", author: "Dr. Seuss" }],
    "Anxious & Stressed": [{ text: "Nothing diminishes anxiety faster than action.", author: "Walter Anderson" }],
    "Nostalgic & Reflective": [{ text: "The value of a moment, until it becomes a memory.", author: "Dr. Seuss" }],
    "Tired & Burned Out": [{ text: "Almost everything will work again if you unplug it.", author: "Anne Lamott" }]
};